In [1]:
import numpy as np

In [2]:
w = np.array([[1,2],[2,3]])

In [3]:
w.shape

(2, 2)

In [13]:
w = np.array([[1,1],[2,2],[3,3]])

In [19]:
w.shape

(3, 2)

In [20]:
w.mean(1)

array([1., 2., 3.])

In [27]:
e = np.random.rand(5,3,1)

In [26]:
e.mean(1).shape

(5, 512)

In [2]:
import torch

In [25]:
w = torch.rand(2,2,5)
x = torch.ones(2,1,5)

In [26]:
w

tensor([[[0.4062, 0.2620, 0.4179, 0.3609, 0.1414],
         [0.4604, 0.8161, 0.2361, 0.5083, 0.8266]],

        [[0.0491, 0.5496, 0.7397, 0.1028, 0.3780],
         [0.3949, 0.9198, 0.4588, 0.8062, 0.3510]]])

In [27]:
x

tensor([[[1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.]]])

In [39]:
torch.argmax(torch.sum(w*x,2),1)

tensor([1, 1])

In [41]:
torch.sum(w*x,2).shape

torch.Size([2, 2])

In [113]:
t = torch.rand([2,7])

In [77]:
w = torch.rand(10)

In [78]:
t = w.view(2,5)

In [111]:
w = torch.rand(2,7,10)

In [118]:
e = torch.ones(2).long()

In [128]:
e = e.reshape(2,1)

In [129]:
w[e].shape

torch.Size([2, 1, 7, 10])

In [131]:
w.shape

torch.Size([2, 7, 10])