In [1]:
import numpy as np

In [2]:
w = np.array([[1,2],[2,3]])

In [3]:
w.shape

(2, 2)

In [13]:
w = np.array([[1,1],[2,2],[3,3]])

In [19]:
w.shape

(3, 2)

In [20]:
w.mean(1)

array([1., 2., 3.])

In [27]:
e = np.random.rand(5,3,1)

In [26]:
e.mean(1).shape

(5, 512)

In [14]:
import numpy as np
import torch 

In [11]:
w = np.ones(10).reshape(10,1)
q = np.ones(5).reshape(1,5)

In [16]:
a = torch.ones(10,1)
b = torch.ones(1,5)

In [21]:
torch.eq(a,b)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.uint8)

In [35]:
w.shape

torch.Size([2, 3, 40, 40])

In [6]:
w.mean(1)

tensor([[0.4275],
        [0.4178],
        [0.5017]])

In [42]:
upsample = torch.nn.Upsample(size=[224,224], scale_factor=None, mode='bilinear', align_corners=None)

In [43]:
upsample(w).shape

torch.Size([2, 3, 224, 224])