In [1]:
import numpy as np

In [2]:
w = np.array([[1,2],[2,3]])

In [3]:
w.shape

(2, 2)

In [13]:
w = np.array([[1,1],[2,2],[3,3]])

In [19]:
w.shape

(3, 2)

In [20]:
w.mean(1)

array([1., 2., 3.])

In [27]:
e = np.random.rand(5,3,1)

In [26]:
e.mean(1).shape

(5, 512)

In [28]:
e

array([[[0.01597561],
        [0.64425098],
        [0.17915364]],

       [[0.52408952],
        [0.22101032],
        [0.872804  ]],

       [[0.12944336],
        [0.95019055],
        [0.38425907]],

       [[0.66262946],
        [0.36141646],
        [0.05841169]],

       [[0.89354701],
        [0.73788645],
        [0.41238656]]])

In [1]:
import torch

In [34]:
w = torch.rand(2,3,40,40)

In [35]:
w.shape

torch.Size([2, 3, 40, 40])

In [6]:
w.mean(1)

tensor([[0.4275],
        [0.4178],
        [0.5017]])

In [42]:
upsample = torch.nn.Upsample(size=[224,224], scale_factor=None, mode='bilinear', align_corners=None)

In [43]:
upsample(w).shape

torch.Size([2, 3, 224, 224])